[package]
name = "maze-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["cargo"] }
hashbrown = "0.13.2"
priority-queue = "1.3.1"
rustc-hash = "1.1.0"

[profile.release]
lto = true
panic = "abort"
